# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_author_number_of_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
